name: Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-native:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    - name: Build native
      run: |
        make clean || true
        make
        
    - name: Test native binary
      run: |
        ./tree --help
        ./tree --version
        ./tree -L 1 .
        
    - name: Upload native binary
      uses: actions/upload-artifact@v4
      with:
        name: tree-native-test
        path: tree
        retention-days: 7
